server:
  port:
    9191

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-identity-api
          uri: lb://user-identity-api
          predicates:
            - Path=/user-identity/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-identity-api
                fallbackuri: forward:/serviceFallback
        - id: messaging-api
          uri: lb://messaging-api
          predicates:
            - Path=/messaging/**
          filters:
            - name: CircuitBreaker
              args:
                name: messaging-api
                fallbackuri: forward:/serviceFallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost