spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ramble_iam_db
    username: ramble_user
    password: JhlOYzexiu4o1ChGHJTwCw==
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update