spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ashish.kr.jha89@gmail.com
    password: incorrect_password

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000