server:
  port:
    9001

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ramble_iam_db
    username: ramble_user
    password: JhlOYzexiu4o1ChGHJTwCw==
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: USER-IDENTITY-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost