email-sender:
  enableVault: false
  vaultPath: kv/email-sender
  host: localhost
  port: 1025
  transportProtocol: smtp
  smtpAuth: true
  startTlsEnabled: true
  startTlsRequired: true
  connectionTimeout: 5000
  timeout: 3000
  writeTimeout: 5000

jwt:
  signingKeyRefreshToken: oCVm82o74dGKjKyKS/GLeK3HfJD4p7py4AWJI9TZzQj4y4isudcXWf2N8DWYX6uAEQS7hfSAaRVIp42
  signingKeyRegistrationToken: 838ff02eaa64283e369d61324661707338c1da60edbb48aa188bfcd993ffeead5b006bd4

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ramble_iam_db
    username: ramble_user
    password: JhlOYzexiu4o1ChGHJTwCw==
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update